[package]
name = "quex"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.1"
askama_axum = "0.4.0"
axum = "0.7.5"
axum-extra = { version = "0.9.3", features = ["cookie"] }
dotenv = "0.15.0"
libsql = "0.3.5"
serde = "1.0.201"
time = "0.3.36"
tokio = { version = "1.37.0", features = ["full"] }
